server:
  port: 9999
  servlet:
    context-path: /works
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/works?useSSL=false&characterEncoding=utf8
    username: root
    password: agytorudhcv11
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    database: 1
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 2
        max-active: 8
  session:
    store-type: none