server:
  port: 9999
  servlet:
    context-path: /mail

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mail?useSSL=false&characterEncoding=utf8
    username: root
    password: agytorudhcv11
    driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false


  redis:
    database: 1
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 2
        max-active: 8
  session:
    store-type: none

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false